name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  scrub:
    runs-on: ubuntu-latest
    steps:
      - name: Compute fetch depth
        id: fetch-depth
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "depth=$(( ${{ github.event.pull_request.commits }} + 1 ))" >> "$GITHUB_OUTPUT"
          else
            echo "depth=0" >> "$GITHUB_OUTPUT"
          fi
      - uses: actions/checkout@v6
        with:
          fetch-depth: ${{ steps.fetch-depth.outputs.depth }}
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Scrub commit history
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            NIX_FLAKE_SHALLOW=1 nix run '.?shallow=1#scrub-commit-history' -- --git --forward --parallel --keep-going --print-build-logs \
              '${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}'
          else
            NIX_FLAKE_SHALLOW=1 nix run '.?shallow=1#scrub-commit-history' -- --git --forward --parallel --keep-going --print-build-logs
          fi
